-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 13:34:06 2020
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asset_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seminar_management` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `seminar_management` ;

-- -----------------------------------------------------
-- Table `asset_management`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminar_management`.`education` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asset_management`.`storage_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminar_management`.`occupation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asset_management`.`asset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `seminar_management`.`participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `email` VARCHAR(150) NULL,
  `phone` VARCHAR(150) NULL,
  `education_id` INT NOT NULL,
  `occupation_id` INT NOT NULL,
  `address` TEXT NULL,
  `birth_date` DATE NULL,
  `sex` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_participant_education_idx` (`education_id` ASC),
  INDEX `fk_participant_occupation_idx` (`occupation_id` ASC),
  CONSTRAINT `fk_participant_education`
    FOREIGN KEY (`education_id`)
    REFERENCES `seminar_management`.`education` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant_occupation`
    FOREIGN KEY (`occupation_id`)
    REFERENCES `seminar_management`.`occupation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
